spring:
  application:
    name: Coupon-API
  datasource:
    url: jdbc:h2:mem:coupondb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

coupon:
  openapi:
    title: "Coupon API"
    description: "API para cadastro e remoção de cupons de desconto"
    version: "v1"